version: 2

project_name: pudding

builds:
  - main: ./main.go
    binary: pd
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - repository:
      owner: heycomputer
      name: homebrew-tools
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: GitHub Actions
      email: actions@github.com
    description: "Use version-aware fuzzy-search to quickly find the _right_ documentation from your project's dependencies and cache them locally for fast access anytime."
    homepage: "https://github.com/heycomputer/pudding"
    license: MIT
